language: c
dist: xenial
sudo: required

branches:
  except:
  - "/^feature.*$/"
  - "/^fix.*$/"
  - "gh-pages"
git:
  depth: 9999999
matrix:
  include:

# Coverity build, must be the first!
  - os: linux
    compiler: gcc
    env:
      - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-5.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    addons:
      coverity_scan:
        project:
          name: gatzka/sclog
          description: Build submitted via Travis CI
        notification_email: stephan.gatzka@gmail.com
        #build_script_url: https://raw.githubusercontent.com/gatzka/sclog/coverity_scan/.travisci_build_coverity_scan.sh
        build_command_prepend: "cov-configure --comptype gcc"
        build_command: cmake -DCMAKE_BUILD_TYPE:STRING=Debug ./ ; cmake --build ./
        branch_pattern: coverity_scan
      apt:
        packages:
        - cmake
        - curl
        - ca-certificates
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-5.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        packages:
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-6.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - gcc-6
        - g++-6
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-6.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - gcc-6
        - g++-6
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-7.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - gcc-7
        - g++-7
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-7.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - gcc-7
        - g++-7
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=ON"
    - BUILD_WITH_COVERAGE_INFO=1
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - gcc-8
        - g++-8
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-gcc-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF -DSCLOG_CTEST_DOCUMENTATION:BOOL=ON"
    - CREATE_DOXY=true
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - cmake
        - cmake-data
        - doxygen
        - gcc-8
        - g++-8
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-6.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-6.0
        packages:
        - clang-6.0
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-6.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-6.0
        packages:
        - clang-6.0
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-7.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        packages:
        - clang-7
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-7.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        packages:
        - clang-7
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: gcc
    script:
    - cmake -DCMAKE_C_COMPILER:STRING=gcc -DCMAKE_CXX_COMPILER:STRING=g++ -DCMAKE_BUILD_TYPE:STRING=Debug ./
    - build-wrapper-linux-x86-64 --out-dir bw-output make
    - sonar-scanner
    addons:
      sonarcloud:
        organization: "gatzka-github"
        token:
          secure: "h5ClQS3t+T2buKQivnU9+9XRQucU+54MN4n3lWk0h6MK8VbDlLECoduus+iGyjyUzNDmG99z7Kn5DbE201ZQhaozNk2Z4JU5bzf5NUPW2yk9YaAuqpC/S6i9YyeKLtwe9GsFHbirxmwLxtqx9hU10Hxb9Tm1Pr6RFWkN2KW0cUldyyWRgZ96i3dUPBkL7mflk2GtSjJWHaju6aDYTyQWv8fdBJvtXxALb9TSFDM0+mQ3q9+k/Wz5VIkOk19YDTI3pA53/315UJ+xZzERcTiiePFNzGHN7sso7HLTTTwlQ0UU2tdyXUpwTMlaW4KPXsAF9w2tV4RkUueKMixthMTsscdcTqkCVa8LkaD0gwOQm9oPghN7STbbSLqFPTQup3LAe9uSVjGNjEhehXNMW6wdYi2Tw5jKtuaZcp+N9oDVRgnf0wTnaKLez6/WvPom3OyE4rQnM/DTwm4Nozljo/OouyPwXVYhRK38VX7Ee99EmayuRAXDUsMJDKawrDp0jDmxkWKyAYMatfsBCzSY0ngIb4yx6PYWBBt1HZYm5P1TsmQ8/Tr25Vgo60R/b7kKZGjNi8xsdq/9Jufb+/RWTNudIHJhpTFzWttK6siXWE2CLC4hwiqN+Adl6frmk2kjvB9hzGomPGiYvrEX0012b292ynEitOPmVyMOExsJ3YLTuW4="
      cache:
        directories:
          - '$HOME/.sonar/cache'
      apt:
        packages:
        - cmake
        - cmake-data
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_ANALYZER:STRING=scan-build-8 -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - clang-tools-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_ANALYZER:STRING=clang-tidy-8 -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Debug -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - clang-tidy-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_SANITIZER:STRING=UndefinedBehaviorSanitizer -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_SANITIZER:STRING=LeakSanitizer -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_SANITIZER:STRING=MemorySanitizer -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

  - os: linux
    compiler: clang
    env:
    - MATRIX_EVAL="-DSCLOG_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/x86-linux-clang-8.cmake -DSCLOG_CTEST_CONFIGURATION_TYPE:STRING=Release -DSCLOG_CTEST_SANITIZER:STRING=AddressSanitizer -DSCLOG_CTEST_COVERAGE:BOOL=OFF"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        packages:
        - clang-8
        - cmake
        - cmake-data
        - ninja-build
        - libsystemd-dev

install:
- pip install --user gcovr

script:
- if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
    ctest -VV -S build.cmake ${MATRIX_EVAL};
  fi

after_success:
- if [ -n "${BUILD_WITH_COVERAGE_INFO}" ]; then
    bash <(curl -s https://codecov.io/bash) -s /tmp/sclog/ || echo "Codecov did not collect coverage reports";
  fi

- if [ -n "${CREATE_DOXY}" ]; then
    $TRAVIS_BUILD_DIR/scripts/push-doxygen-to-gh-pages.sh ;
  fi

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key
  - secure: "Ep3dceb0mD05R5tx0jwWnozgpnPFV8xTEaHxCNif/DtugJ9Dqy6LvNrClKf/fd+e8xD3Me3AGsUsY+sO/o9DPPLAk1NIjwo8QqXaAozFlARYS6Pe9FudfiB8IIF8dgyehN8rnZtmlFHWbAGvQ+3Cp2HhmtepXsZw+RizXUMsUK+lJrQxhuBggs9AeZ+zEXutGp9O1Dr2sYtOl3Oh0ABfloOnHCRPivYvViN029e911k9q/hL+z0UwrumHNNQ728+rVGmBqqcuMPXolQDeQxNg78sixzLfz0t+tgYCg/JbubRXy8o2Et2bbsJMF4qn+2Yi6sQbSGz+QqCfv2Cudn9MWaBp5Ou8J8F78h5tSpWDEMtgOHY0gw9D0uCBZIfZ3XPKyavmUWEphjfk1/OwDSRgPBnL8A9BiADVD2P4XXcGPzd5rAYQBMkTf1QRTF4TaxS4eAzkPkzOR4LurErohwkBE60aJTD+oGrztgGhGjSRl2yCyQJTcT/HWzK0XqmHW3RUcbGv72imJrhkteB/85tBKMC2wua6A2vQh0ajEcRzWI7sOpjkKWfU3WRSez5+nqzsNOkvaWrs1A+E2ynzsUxVTkMMB5XnGJk0B7q1czXSeC/8rNfb0TsvWTtNeD2yGRd7Iu+kJkjcmelL/IBlydAndlTqwZ8dTgDBsCddTkhACk="

